-- SoulFlame EchoProfile V16 Supabase Schema

create table if not exists profiles (
  id bigint primary key,
  created_at timestamptz default now(),
  name text,
  contact text,
  goal text,
  age text,
  main_trait text,
  second_trait text,
  profile text,
  scores jsonb,
  mini_report text,
  full_report text,
  raw jsonb
);

create table if not exists leads (
  id bigint primary key,
  created_at timestamptz default now(),
  offer text,
  name text,
  contact text,
  profile text,
  scores jsonb,
  raw jsonb
);

create table if not exists payments (
  id bigint primary key,
  created_at timestamptz default now(),
  status text default 'pending',
  offer text,
  amount text,
  method text,
  name text,
  contact text,
  code text,
  raw jsonb
);

create table if not exists unlock_codes (
  id bigint primary key,
  created_at timestamptz default now(),
  code text unique not null,
  status text default 'unused',
  offer text,
  note text,
  used_at timestamptz,
  used_by jsonb,
  profile_id bigint,
  payment_id bigint,
  raw jsonb
);

create table if not exists events (
  id bigint primary key,
  created_at timestamptz default now(),
  type text,
  payload jsonb,
  raw jsonb
);

create table if not exists admin_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  action text,
  payload jsonb
);

alter table profiles enable row level security;
alter table leads enable row level security;
alter table payments enable row level security;
alter table unlock_codes enable row level security;
alter table events enable row level security;
alter table admin_logs enable row level security;
